### PR TITLE
How to use your project?

### PR DESCRIPTION
**Pull request by gnatyukv**
How to use your project? Can your project be integrated / compiled in Keil IDE with C51 / C99 compiler?

### CODE REVIEW

**Comment by TorstenRobitzki** [comment]
Hi Vitya,
it depends on your needs. To compile Bluetoe, you need a C++11 compiler. According to this here http://www.keil.com/support/man/docs/armcc/armcc_chr1407404265784.htm. Keil does not fully support C++11. But I think it could be that it supports enough C++11 to compiler Bluetoe.

Second, you need hardware support by Bluetoe. Currently there is only support for the nrf51/nrf52 family from nordic.

To use bluetoe, you have to add the installation path to your include path and compile and link a few cpp files from the bluetoe/link_layer and bluetoe/bindings folders. I'm not familiar with your IDE. But you can find examples using gcc and cmake in the examples folder.

hth
Torsten

**Comment by gnatyukv** [comment]
Hi again. I compiled it with msys32 tool and arm-none-eabi compiler and it does not work (thermometer and blinky). Even no advertising. Can you tell me about more detail suggestions? Maybe I skip some important steps.

**Comment by TorstenRobitzki** [comment]
It compiles and links, but when flashing the firmware, it doesn't send advertising packages?

**Comment by gnatyukv** [comment]
Yes, not visible in Android.

**Comment by TorstenRobitzki** [comment]
Ok, I tried it on my own: 
* first, in the current version, there is a file missing (I've fixed that).
* When I use a BLE sniffer, I see advertising PDUs
* When I use a Nexus 5X (android 6), I don't see the device as pairable device
* When I use (for example) the nRF Master, I can see the device and connect to it.

**Comment by TorstenRobitzki** [comment]
If you give me an email address, I could send you my hex file.

**Comment by gnatyukv** [comment]
Yes, thanks.
gnatyukvv@gmail.com

**Pull request closed without merging**
