### PR TITLE
Sm

### PR DESCRIPTION
**Pull request by TorstenRobitzki**
First version of a Security Manager.

### CODE REVIEW

**Comment by TorstenRobitzki** [comment]
Not ready to be merged. But I want the CI to run on it.

**Comment by TorstenRobitzki** [comment]
This pull request **introduces 1 alert** when merging d98f2f63e312a75c10e40c190378cfee29e611b1 into 9118f1a58610fc07fbdcca0f52169b701ba0ea11 - [view on LGTM.com](https://lgtm.com/projects/g/TorstenRobitzki/bluetoe/rev/pr-ad8e6af3895455ea68a827e8a5cbad77f5ec10bc)

**new alerts:**

* 1 for Empty branch of conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by xnlcasad** [comment]
Are you planning to merge the whole pack of commits ? Or will you do some squashing/polishing first ?

**Comment by TorstenRobitzki** [comment]
Well, I would love to just merge the whole PR. What are you suggesting? Otherwise, it will become one giant commit.

**Comment by TorstenRobitzki** [comment]
If you can take the time to polish the history a little bit, then I can hold back the merge until you are done with the polishing.

**Comment by TorstenRobitzki** [comment]
Current state is, that the examples have to use libnano and the example specific assert() version to fit into flash.

**Pull request closed without merging**
